import Head from 'next/head'
export default function Home() {
  return (
    <>
      <Head>
        <title>That Mobile Height Problem</title>
        <meta name="description" content="Generated by the internet" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <h1>Hello</h1>
      </>
  )
}
